### ISSUE TITLE
Port to MacOS possible?

### ISSUE THREAD

**Issue by assist726** [mayanez/dumang-keyboard-ctrl#1]
Awesome for having this up, any news on if we could get a Mac version of this available?

**Comment by mayanez** [comment]
It should be fairly straightforward. 
I know the `hidapi` is compatible. I would need to find an alternative to Linux's `udev` to detect the keyboard halves being connected.

**Comment by mayanez** [comment]
Looked into this a bit. I think the best approach is to actually make use of `libusb`'s hotplug functionality. From my understanding it should work on both Linux and Mac, so ultimately it can be used to as an alternative to `udev` as well. A good starting point would be this [example code](https://github.com/vpelletier/python-libusb1/blob/master/examples/hotplug_advanced.py).

I don't think I'll have time to get until at least a few weeks. Please feel free to submit a PR if you get to it before me.

**Comment by assist726** [comment]
Example code looks straight forward enough, never written anything similar but will certainly give it a go on the weekend!

**Comment by voltaireodactyl** [comment]
@assist726 any chance you were able to take a crack at this? I just received my DK6 and am most bummed at having not realized the halves  wouldn't communicate modifier keys to each other. 

I have very little coding experience but I want this to work so badly I'm willing to try -- but if people who actually know what they're doing are already doing it, that'd be much easier :)

**Comment by assist726** [comment]
> 
> 
> @assist726 any chance you were able to take a crack at this? I just received my DK6 and am most bummed at having not realized the halves wouldn't communicate modifier keys to each other.
> 
> I have very little coding experience but I want this to work so badly I'm willing to try -- but if people who actually know what they're doing are already doing it, that'd be much easier :)

Apologies never got around to doing this, however there is an easy fix for the modifier key issue. Go download Karabiner Elements and start it up, make sure both halves of the keyboard are ticked within the device list and you're good to go!

**Comment by voltaireodactyl** [comment]
Dude. Thank you so much. No idea how that didn't come up in my searches, but thank you for solving the ONLY issue I had with this sucker.

> Apologies never got around to doing this, however there is an easy fix for the modifier key issue. Go download Karabiner Elements and start it up, make sure both halves of the keyboard are ticked within the device list and you're good to go!

**Comment by mayanez** [comment]
> 
> 
> > @assist726 any chance you were able to take a crack at this? I just received my DK6 and am most bummed at having not realized the halves wouldn't communicate modifier keys to each other.
> > I have very little coding experience but I want this to work so badly I'm willing to try -- but if people who actually know what they're doing are already doing it, that'd be much easier :)
> 
> Apologies never got around to doing this, however there is an easy fix for the modifier key issue. Go download Karabiner Elements and start it up, make sure both halves of the keyboard are ticked within the device list and you're good to go!

I also haven't been able to get to this as I've been busy wrapping up my dissertation. I promise once I get done with that I'll tackle this on a free weekend. 

Also, just curious is it that Karabiner Elements has support for the DK6 or something else I'm missing?

**Comment by assist726** [comment]
> > > @assist726 any chance you were able to take a crack at this? I just received my DK6 and am most bummed at having not realized the halves wouldn't communicate modifier keys to each other.
> > > I have very little coding experience but I want this to work so badly I'm willing to try -- but if people who actually know what they're doing are already doing it, that'd be much easier :)
> > 
> > 
> > Apologies never got around to doing this, however there is an easy fix for the modifier key issue. Go download Karabiner Elements and start it up, make sure both halves of the keyboard are ticked within the device list and you're good to go!
> 
> I also haven't been able to get to this as I've been busy wrapping up my dissertation. I promise once I get done with that I'll tackle this on a free weekend.
> 
> Also, just curious is it that Karabiner Elements has support for the DK6 or something else I'm missing?

Karabiner elements doesn't have special support for Dumang but it seems to be able to override the system level device detection so that you can select both halves to be recognised as a keyboard together.

I suppose with this there's no need to deal with the two halves pairing anymore, would just need some GUI to access key reassignments and macros

**Comment by mayanez** [comment]
Interesting. You could try to see if the rough GUI I built works on Mac.
You can run it with` $ python -m dumang_ctrl.tools.config`. You can use that to inspect the IDs for the physical keys and then program the key mappings via a file.

**Comment by assist726** [comment]
@mayanez Just got it running and the dump seems to work correctly.
I'm a bit confused on how to set up the config.yml, am I supposed to save the dump results into the yml? Would appreciate if you could link a sample yml.

The GUI also seems to load as well however the hover to pulse LED doesn't seem to work correctly, and now all my keys are just continually pulsing after I closed the GUI.

Unfortunately I've just realised Karabiner can deal with regular modifiers going across keyboards but doesn't solve the layers issue across keyboards. I just never noticed since I had my layers keys all on the same side.

**Comment by mayanez** [comment]
@assist726 Strange that the hover for the LED doesn't seem to work for you. At least for me, I just verified it stops blinking once you hover away from the key. It might be they changed the firmware compared to the version I'm currently running. 

There's a minimal `config.yml` file here: https://github.com/mayanez/dumang-keyboard-ctrl/blob/master/config.yml.
It works as follows: 
- The `serial` corresponds to the unique identifier for each keyboard half. 
- Under `keys` you can list out the configuration you want to override for each key according to it's unique key module ID (eg. `key_00` in the file above).
- Each key can be assigned up to 4 layers (eg. `layer_0` - `layer_3`). The values for which map to the following: https://github.com/mayanez/dumang-keyboard-ctrl/blob/master/python/dumang_ctrl/dumang/common.py#L35 

To identify the key module ID (ie. what `key_00` is on your keyboard) you'll either want to use the GUI or inspect the dump to figure it out by looking at what layer_0 is currently configured to for the key you want to change. For example, if I want to change what is currently my `7` key, I'd search for the key ID that has layer 0 set to `SEVEN` (eg. `KeyReportResponsePacket - CMD:05 Key:00 LayerKeycodes:{0: SEVEN, 1: F7, 2: UNKNOWN, 3: UNKNOWN}` in the dump output).

Once you've figured out your `config.yml` you can use the `config` command to write it. It will only write the keys that are specified in the file, all other keys will be unaffected. I suggest you do try a single key so you get the general flow. It's not the most user friendly workflow since I've mostly focused on reversing the protocol so far. 

Note that as the `TODO` currently states, the keymap is still missing a few keys, specifically the layer function keys. I have yet to reverse the key codes assigned to those. Contributions for this are welcome if you have a bit of know-how. You would  need to snoop on the USB traffic to the keyboard on Windows to see what the configuration software ends up writing. I used [this tool ](https://www.usblyzer.com/) on my initial development run.

**Comment by mayanez** [comment]
@kachus22 thanks for the really clean PR! I will be updating the PyPI package soon with the latest version.
